<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { Plus, Refresh, Search } from "@element-plus/icons-vue";
import { api } from "@/api";
import StatusTag from "@/components/StatusTag.vue";
import type { Patient } from "@/types";

const loading = ref(false); const items = ref<Patient[]>([]); const total = ref(0); const dialog = ref(false);
const query = reactive({ page: 1, pageSize: 10, keyword: "", gender: "", status: "" });
const form = reactive<Partial<Patient>>({ patientCode: "", name: "", gender: "unknown", educationYears: null, birthDate: null, status: "active", profile: {} });
async function load() { loading.value = true; try { const result = await api.patients(query); items.value = result.items; total.value = result.total; } finally { loading.value = false; } }
function open(patient?: Patient) { Object.assign(form, patient ?? { patientId: undefined, patientCode: "", name: "", gender: "unknown", educationYears: null, birthDate: null, status: "active", profile: {} }); dialog.value = true; }
async function save() { if (!form.patientCode || !form.name) return ElMessage.warning("请填写患者编号和姓名"); await api.savePatient(form as Patient); ElMessage.success("保存成功"); dialog.value = false; load(); }
async function remove(patient: Patient) { try { await ElMessageBox.confirm(`确认删除患者 ${patient.name}？`, "删除确认", { type: "warning" }); await api.deletePatient(patient.patientId); ElMessage.success("删除成功"); load(); } catch (error) { if (error instanceof Error) ElMessage.error(error.message); } }
function reset() { Object.assign(query, { page: 1, keyword: "", gender: "", status: "" }); load(); }
onMounted(load);
</script>
<template><div class="page-stack"><section class="panel filter-panel"><div class="filter-row"><el-input v-model="query.keyword" placeholder="患者姓名或编号编号" clearable :prefix-icon="Search" @keyup.enter="load" /><el-select v-model="query.gender" placeholder="性别" clearable><el-option label="男" value="male" /><el-option label="女" value="female" /><el-option label="未知" value="unknown" /></el-select><el-select v-model="query.status" placeholder="状态" clearable><el-option label="活跃" value="active" /><el-option label="已归档" value="archived" /></el-select><el-button type="primary" :icon="Search" @click="load">查询</el-button><el-button :icon="Refresh" @click="reset">重置</el-button><div class="filter-spacer" /><el-button type="primary" :icon="Plus" @click="open()">新增患者</el-button></div></section>
<section class="panel table-panel"><div class="panel-heading"><div><h3>患者档案</h3><p>共 {{ total }} 条患者记录</p></div></div><el-table v-loading="loading" :data="items" stripe><el-table-column prop="patientCode" label="患者编号" min-width="150" /><el-table-column prop="name" label="姓名" min-width="110" /><el-table-column label="性别" width="80"><template #default="scope">{{ scope.row.gender === 'male' ? '男' : scope.row.gender === 'female' ? '女' : '未知' }}</template></el-table-column><el-table-column prop="birthDate" label="出生日期" width="120" /><el-table-column prop="educationYears" label="受教育年限" width="110" /><el-table-column label="来源" min-width="110"><template #default="scope">{{ scope.row.profile.source ?? '--' }}</template></el-table-column><el-table-column label="状态" width="90"><template #default="scope"><StatusTag :status="scope.row.status" /></template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="scope"><el-button link type="primary" @click="open(scope.row)">编辑</el-button><el-button link type="danger" @click="remove(scope.row)">删除</el-button></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="query.page" v-model:page-size="query.pageSize" layout="total, prev, pager, next" :total="total" @current-change="load" /></div></section>
<el-dialog v-model="dialog" :title="form.patientId ? '编辑患者' : '新增患者'" width="620px"><el-form :model="form" label-width="100px" class="dialog-form"><el-form-item label="患者编号" required><el-input v-model="form.patientCode" /></el-form-item><el-form-item label="姓名" required><el-input v-model="form.name" /></el-form-item><el-form-item label="性别"><el-radio-group v-model="form.gender"><el-radio value="male">男</el-radio><el-radio value="female">女</el-radio><el-radio value="unknown">未知</el-radio></el-radio-group></el-form-item><el-form-item label="出生日期"><el-date-picker v-model="form.birthDate" type="date" value-format="YYYY-MM-DD" /></el-form-item><el-form-item label="受教育年限"><el-input-number v-model="form.educationYears" :min="0" :max="40" /></el-form-item><el-form-item label="状态"><el-select v-model="form.status"><el-option label="活跃" value="active" /><el-option label="归档" value="archived" /></el-select></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></div></template>
