-- ============================================================================
-- 认知障碍评估量表评分系统 —— 种子数据（6 个量表配置）
-- 本文件由 scripts/generate_seed_sql.py 依据 scoring/config_data.py 自动生成。
-- 数据出处：PDF 量表原始资料（SCD-Q9 / MMSE / GDS / FAQ / MoCA-B / CDR）。
-- ============================================================================
SET NAMES utf8mb4;
START TRANSACTION;

-- --------------------------------------------------------------------------
-- 量表：主观认知下降自测表（SCD_Q9）  计分类型：SUM
-- --------------------------------------------------------------------------
INSERT INTO `scale` (`id`,`code`,`name`,`full_name`,`version`,`summary`,`instruction`,`scoring_type`,`score_min`,`score_max`,`remark`) VALUES (1,'SCD_Q9','主观认知下降自测表','Subjective Cognitive Decline Questionnaire (SCD-Q9)','1.0','用于筛查老年人主观认知下降（SCD）的自测量表，共 9 个条目。','请根据自身实际情况作答。评分标准：是=1分、否=0分；经常=1分、偶尔=0.5分、从未=0分。最后得分=各题得分之和（0~9分）。','SUM',0.0,9.0,'参考评分标准见量表原版；本量表总分越高提示主观记忆下降越明显。');
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (1,1,'SCD_Q9_01',1,NULL,'你认为自己有记忆问题吗？','单选','DIRECT',1.0,1,1,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (1,1,'是','是',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (2,1,'否','否',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (2,1,'SCD_Q9_02',2,NULL,'你回忆 3-5 天前的对话有困难吗？','单选','DIRECT',1.0,1,2,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (3,2,'是','是',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (4,2,'否','否',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (3,1,'SCD_Q9_03',3,NULL,'你觉得自己近两年有记忆问题吗？','单选','DIRECT',1.0,1,3,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (5,3,'是','是',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (6,3,'否','否',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (4,1,'SCD_Q9_04',4,NULL,'下列问题经常发生吗：忘记对个人来说重要的日期（如生日等）','单选','DIRECT',1.0,1,4,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (7,4,'经常','经常',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (8,4,'偶尔','偶尔',0.5,0,1);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (9,4,'从未','从未',0.0,0,2);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (5,1,'SCD_Q9_05',5,NULL,'下列问题经常发生吗：忘记常用号码','单选','DIRECT',1.0,1,5,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (10,5,'经常','经常',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (11,5,'偶尔','偶尔',0.5,0,1);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (12,5,'从未','从未',0.0,0,2);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (6,1,'SCD_Q9_06',6,NULL,'总的来说，你是否认为自己对要做的事或要说的话容易忘记？','单选','DIRECT',1.0,1,6,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (13,6,'是','是',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (14,6,'否','否',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (7,1,'SCD_Q9_07',7,NULL,'下列问题经常发生吗：到了商店忘记要买什么','单选','DIRECT',1.0,1,7,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (15,7,'经常','经常',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (16,7,'偶尔','偶尔',0.5,0,1);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (17,7,'从未','从未',0.0,0,2);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (8,1,'SCD_Q9_08',8,NULL,'你认为自己的记忆力比 5 年前要差吗？','单选','DIRECT',1.0,1,8,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (18,8,'是','是',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (19,8,'否','否',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (9,1,'SCD_Q9_09',9,NULL,'你认为自己越来越记不住东西放哪儿了吗？','单选','DIRECT',1.0,1,9,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (20,9,'是','是',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (21,9,'否','否',0.0,0,1);

-- --------------------------------------------------------------------------
-- 量表：老年抑郁量表（GDS）  计分类型：SUM
-- --------------------------------------------------------------------------
INSERT INTO `scale` (`id`,`code`,`name`,`full_name`,`version`,`summary`,`instruction`,`scoring_type`,`score_min`,`score_max`,`remark`) VALUES (2,'GDS','老年抑郁量表','Geriatric Depression Scale (GDS-15)','1.0','Brink 等 1982 年编制，专用于老年人的抑郁筛查表，共 15 个条目（是/否）。','选择最切合你最近一周感受的答案。15 个条目中有 5 条反序计分（回答「否」表示抑郁存在），10 条正序计分（回答「是」表示抑郁存在）。','SUM',0.0,15.0,'反序计分题：第 1、5、7、11、13 题。');
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (10,2,'GDS_01',1,NULL,'你对你的生活基本满意吗？','单选','DIRECT',1.0,1,1,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (22,10,'是','是',0.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (23,10,'否','否',1.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (11,2,'GDS_02',2,NULL,'你是否已经放弃了许多爱好与兴趣？','单选','DIRECT',1.0,1,2,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (24,11,'是','是',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (25,11,'否','否',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (12,2,'GDS_03',3,NULL,'你是否觉得生活空虚？','单选','DIRECT',1.0,1,3,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (26,12,'是','是',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (27,12,'否','否',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (13,2,'GDS_04',4,NULL,'你是否感到厌倦？','单选','DIRECT',1.0,1,4,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (28,13,'是','是',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (29,13,'否','否',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (14,2,'GDS_05',5,NULL,'你是否大部分时间精力充沛？','单选','DIRECT',1.0,1,5,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (30,14,'是','是',0.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (31,14,'否','否',1.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (15,2,'GDS_06',6,NULL,'你是否害怕会有不幸的事落到你头上？','单选','DIRECT',1.0,1,6,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (32,15,'是','是',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (33,15,'否','否',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (16,2,'GDS_07',7,NULL,'你是否大部分时间感到幸福？','单选','DIRECT',1.0,1,7,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (34,16,'是','是',0.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (35,16,'否','否',1.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (17,2,'GDS_08',8,NULL,'你是否经常感到孤立无援？','单选','DIRECT',1.0,1,8,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (36,17,'是','是',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (37,17,'否','否',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (18,2,'GDS_09',9,NULL,'你是否愿意呆在家里而不愿去室外做些新鲜事？','单选','DIRECT',1.0,1,9,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (38,18,'是','是',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (39,18,'否','否',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (19,2,'GDS_10',10,NULL,'你是否觉得记忆力比以前差？','单选','DIRECT',1.0,1,10,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (40,19,'是','是',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (41,19,'否','否',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (20,2,'GDS_11',11,NULL,'你觉得现在活着很开心吗？','单选','DIRECT',1.0,1,11,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (42,20,'是','是',0.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (43,20,'否','否',1.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (21,2,'GDS_12',12,NULL,'你是否觉得像现在这样活着毫无意义？','单选','DIRECT',1.0,1,12,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (44,21,'是','是',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (45,21,'否','否',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (22,2,'GDS_13',13,NULL,'你觉得生活充满活力吗？','单选','DIRECT',1.0,1,13,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (46,22,'是','是',0.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (47,22,'否','否',1.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (23,2,'GDS_14',14,NULL,'你是否觉得你的处境已毫无希望？','单选','DIRECT',1.0,1,14,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (48,23,'是','是',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (49,23,'否','否',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (24,2,'GDS_15',15,NULL,'你是否觉得大多数人比你强得多？','单选','DIRECT',1.0,1,15,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (50,24,'是','是',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (51,24,'否','否',0.0,0,1);
INSERT INTO `scale_cutoff` (`id`,`scale_id`,`cutoff_type`,`group_key`,`result_label`,`is_abnormal`,`edu_years_min`,`edu_years_max`,`min_score`,`max_score`,`threshold`,`sort_order`) VALUES (1,2,'LEVEL','0-4','正常',0,NULL,NULL,0.0,4.0,NULL,0);
INSERT INTO `scale_cutoff` (`id`,`scale_id`,`cutoff_type`,`group_key`,`result_label`,`is_abnormal`,`edu_years_min`,`edu_years_max`,`min_score`,`max_score`,`threshold`,`sort_order`) VALUES (2,2,'LEVEL','5-8','轻度抑郁',0,NULL,NULL,5.0,8.0,NULL,1);
INSERT INTO `scale_cutoff` (`id`,`scale_id`,`cutoff_type`,`group_key`,`result_label`,`is_abnormal`,`edu_years_min`,`edu_years_max`,`min_score`,`max_score`,`threshold`,`sort_order`) VALUES (3,2,'LEVEL','9-11','中度抑郁',0,NULL,NULL,9.0,11.0,NULL,2);
INSERT INTO `scale_cutoff` (`id`,`scale_id`,`cutoff_type`,`group_key`,`result_label`,`is_abnormal`,`edu_years_min`,`edu_years_max`,`min_score`,`max_score`,`threshold`,`sort_order`) VALUES (4,2,'LEVEL','12-15','重度抑郁',1,NULL,NULL,12.0,15.0,NULL,3);

-- --------------------------------------------------------------------------
-- 量表：功能活动问卷（FAQ）  计分类型：SUM
-- --------------------------------------------------------------------------
INSERT INTO `scale` (`id`,`code`,`name`,`full_name`,`version`,`summary`,`instruction`,`scoring_type`,`score_min`,`score_max`,`remark`) VALUES (3,'FAQ','功能活动问卷','Functional Activity Questionnaire (FAQ)','1.0','Pfeffer 1982 年编制，由知情者完成，用于测定老年人独立生活能力，共 10 个条目。','由知情者完成，评价指标为项目总分。评分 0~3 四级：0=无困难；1=有些困难需指导或监督；2=部分依赖；3=无法完成或完全依赖；NA=该项目不适合或老人从来不做（不计入总分）。','SUM',0.0,30.0,'界值：MCI ≥9 分；SCD 参考范围 6-8 分。');
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (25,3,'FAQ_01',1,NULL,'使用电话或手机','单选','DIRECT',3.0,1,1,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (52,25,'0','没有任何困难，能独立完成，不需他人帮助',0.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (53,25,'1','有些困难，需要他人指导或监督',1.0,0,1);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (54,25,'2','需要帮助才能完成，部分依赖',2.0,0,2);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (55,25,'3','本人无法完成，或完全由他人代替完成',3.0,0,3);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (56,25,'NA','该项目不适合，或老人从来不做',0.0,1,4);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (26,3,'FAQ_02',2,NULL,'整理家庭物品井井有条、不凌乱','单选','DIRECT',3.0,1,2,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (57,26,'0','没有任何困难，能独立完成，不需他人帮助',0.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (58,26,'1','有些困难，需要他人指导或监督',1.0,0,1);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (59,26,'2','需要帮助才能完成，部分依赖',2.0,0,2);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (60,26,'3','本人无法完成，或完全由他人代替完成',3.0,0,3);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (61,26,'NA','该项目不适合，或老人从来不做',0.0,1,4);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (27,3,'FAQ_03',3,NULL,'自行购物（如购买衣服、食品及家庭用品）','单选','DIRECT',3.0,1,3,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (62,27,'0','没有任何困难，能独立完成，不需他人帮助',0.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (63,27,'1','有些困难，需要他人指导或监督',1.0,0,1);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (64,27,'2','需要帮助才能完成，部分依赖',2.0,0,2);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (65,27,'3','本人无法完成，或完全由他人代替完成',3.0,0,3);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (66,27,'NA','该项目不适合，或老人从来不做',0.0,1,4);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (28,3,'FAQ_04',4,NULL,'参加需技巧性的游戏或活动（如打扑克、下棋、打麻将、绘画、摄影、集邮、书法、木工）','单选','DIRECT',3.0,1,4,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (67,28,'0','没有任何困难，能独立完成，不需他人帮助',0.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (68,28,'1','有些困难，需要他人指导或监督',1.0,0,1);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (69,28,'2','需要帮助才能完成，部分依赖',2.0,0,2);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (70,28,'3','本人无法完成，或完全由他人代替完成',3.0,0,3);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (71,28,'NA','该项目不适合，或老人从来不做',0.0,1,4);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (29,3,'FAQ_05',5,NULL,'使用各种电器（如电视、空调、微波炉、电饭煲）','单选','DIRECT',3.0,1,5,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (72,29,'0','没有任何困难，能独立完成，不需他人帮助',0.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (73,29,'1','有些困难，需要他人指导或监督',1.0,0,1);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (74,29,'2','需要帮助才能完成，部分依赖',2.0,0,2);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (75,29,'3','本人无法完成，或完全由他人代替完成',3.0,0,3);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (76,29,'NA','该项目不适合，或老人从来不做',0.0,1,4);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (30,3,'FAQ_06',6,NULL,'准备和烧一顿饭菜（包括加工蔬菜、使用炉子、调味品用量恰当）','单选','DIRECT',3.0,1,6,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (77,30,'0','没有任何困难，能独立完成，不需他人帮助',0.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (78,30,'1','有些困难，需要他人指导或监督',1.0,0,1);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (79,30,'2','需要帮助才能完成，部分依赖',2.0,0,2);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (80,30,'3','本人无法完成，或完全由他人代替完成',3.0,0,3);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (81,30,'NA','该项目不适合，或老人从来不做',0.0,1,4);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (31,3,'FAQ_07',7,NULL,'关心和了解新鲜事物（国家大事或邻居中发生的重要事情）','单选','DIRECT',3.0,1,7,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (82,31,'0','没有任何困难，能独立完成，不需他人帮助',0.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (83,31,'1','有些困难，需要他人指导或监督',1.0,0,1);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (84,31,'2','需要帮助才能完成，部分依赖',2.0,0,2);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (85,31,'3','本人无法完成，或完全由他人代替完成',3.0,0,3);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (86,31,'NA','该项目不适合，或老人从来不做',0.0,1,4);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (32,3,'FAQ_08',8,NULL,'持续一小时以上注意力集中地看电视或小说，或收听收音机并能理解、评论或讨论其内容','单选','DIRECT',3.0,1,8,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (87,32,'0','没有任何困难，能独立完成，不需他人帮助',0.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (88,32,'1','有些困难，需要他人指导或监督',1.0,0,1);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (89,32,'2','需要帮助才能完成，部分依赖',2.0,0,2);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (90,32,'3','本人无法完成，或完全由他人代替完成',3.0,0,3);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (91,32,'NA','该项目不适合，或老人从来不做',0.0,1,4);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (33,3,'FAQ_09',9,NULL,'记得重要的时间点（如领退休金日期、按时服药、领送幼儿等）','单选','DIRECT',3.0,1,9,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (92,33,'0','没有任何困难，能独立完成，不需他人帮助',0.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (93,33,'1','有些困难，需要他人指导或监督',1.0,0,1);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (94,33,'2','需要帮助才能完成，部分依赖',2.0,0,2);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (95,33,'3','本人无法完成，或完全由他人代替完成',3.0,0,3);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (96,33,'NA','该项目不适合，或老人从来不做',0.0,1,4);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (34,3,'FAQ_10',10,NULL,'独自外出活动或走亲访友（指较远距离、如相当于三站公共车辆的距离）','单选','DIRECT',3.0,1,10,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (97,34,'0','没有任何困难，能独立完成，不需他人帮助',0.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (98,34,'1','有些困难，需要他人指导或监督',1.0,0,1);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (99,34,'2','需要帮助才能完成，部分依赖',2.0,0,2);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (100,34,'3','本人无法完成，或完全由他人代替完成',3.0,0,3);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (101,34,'NA','该项目不适合，或老人从来不做',0.0,1,4);
INSERT INTO `scale_cutoff` (`id`,`scale_id`,`cutoff_type`,`group_key`,`result_label`,`is_abnormal`,`edu_years_min`,`edu_years_max`,`min_score`,`max_score`,`threshold`,`sort_order`) VALUES (5,3,'LEVEL','0-5','正常',0,NULL,NULL,0.0,5.0,NULL,0);
INSERT INTO `scale_cutoff` (`id`,`scale_id`,`cutoff_type`,`group_key`,`result_label`,`is_abnormal`,`edu_years_min`,`edu_years_max`,`min_score`,`max_score`,`threshold`,`sort_order`) VALUES (6,3,'LEVEL','6-8','SCD 参考范围',0,NULL,NULL,6.0,8.0,NULL,1);
INSERT INTO `scale_cutoff` (`id`,`scale_id`,`cutoff_type`,`group_key`,`result_label`,`is_abnormal`,`edu_years_min`,`edu_years_max`,`min_score`,`max_score`,`threshold`,`sort_order`) VALUES (7,3,'LEVEL','9-30','MCI（轻度认知损害）',1,NULL,NULL,9.0,30.0,NULL,2);

-- --------------------------------------------------------------------------
-- 量表：简明精神状态检查（MMSE）  计分类型：ITEMIZED
-- --------------------------------------------------------------------------
INSERT INTO `scale` (`id`,`code`,`name`,`full_name`,`version`,`summary`,`instruction`,`scoring_type`,`score_min`,`score_max`,`remark`) VALUES (4,'MMSE','简明精神状态检查','Mini-Mental State Examination (MMSE)','1.0','Folstein 1975 年创立，最常用的认知及智能检查量表，共 30 个条目、30 分。','对患者进行定向、记忆、注意与计算、语言、视空间等 11 个认知域的检查，每题回答正确得 1 分。节点分数：17 分（文盲）、20 分（1-6 年）、24 分（>6 年）。','ITEMIZED',0.0,30.0,'得分 ≤ 对应教育程度界值判为异常（认知障碍筛查阳性）。');
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (35,4,'MMSE_01',1,'时间定向','现在是哪一年？','单选','DIRECT',1.0,1,1,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (102,35,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (103,35,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (36,4,'MMSE_02',2,'时间定向','现在是什么季节？','单选','DIRECT',1.0,1,2,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (104,36,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (105,36,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (37,4,'MMSE_03',3,'时间定向','现在是几月份？','单选','DIRECT',1.0,1,3,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (106,37,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (107,37,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (38,4,'MMSE_04',4,'时间定向','今天是几号？','单选','DIRECT',1.0,1,4,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (108,38,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (109,38,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (39,4,'MMSE_05',5,'时间定向','今天是星期几？','单选','DIRECT',1.0,1,5,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (110,39,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (111,39,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (40,4,'MMSE_06',6,'地点定向','我们现在在什么城市？','单选','DIRECT',1.0,1,6,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (112,40,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (113,40,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (41,4,'MMSE_07',7,'地点定向','在什么城区（区/县）？','单选','DIRECT',1.0,1,7,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (114,41,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (115,41,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (42,4,'MMSE_08',8,'地点定向','在什么街道？','单选','DIRECT',1.0,1,8,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (116,42,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (117,42,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (43,4,'MMSE_09',9,'地点定向','在第几层楼？','单选','DIRECT',1.0,1,9,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (118,43,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (119,43,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (44,4,'MMSE_10',10,'地点定向','这里是什么地方？','单选','DIRECT',1.0,1,10,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (120,44,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (121,44,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (45,4,'MMSE_11',11,'即刻记忆','复述并记住「皮球」','单选','DIRECT',1.0,1,11,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (122,45,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (123,45,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (46,4,'MMSE_12',12,'即刻记忆','复述并记住「国旗」','单选','DIRECT',1.0,1,12,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (124,46,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (125,46,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (47,4,'MMSE_13',13,'即刻记忆','复述并记住「树木」','单选','DIRECT',1.0,1,13,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (126,47,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (127,47,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (48,4,'MMSE_14',14,'注意与计算','100-7=93','单选','DIRECT',1.0,1,14,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (128,48,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (129,48,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (49,4,'MMSE_15',15,'注意与计算','93-7=86','单选','DIRECT',1.0,1,15,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (130,49,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (131,49,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (50,4,'MMSE_16',16,'注意与计算','86-7=79','单选','DIRECT',1.0,1,16,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (132,50,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (133,50,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (51,4,'MMSE_17',17,'注意与计算','79-7=72','单选','DIRECT',1.0,1,17,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (134,51,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (135,51,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (52,4,'MMSE_18',18,'注意与计算','72-7=65','单选','DIRECT',1.0,1,18,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (136,52,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (137,52,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (53,4,'MMSE_19',19,'延迟回忆','回忆「皮球」','单选','DIRECT',1.0,1,19,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (138,53,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (139,53,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (54,4,'MMSE_20',20,'延迟回忆','回忆「国旗」','单选','DIRECT',1.0,1,20,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (140,54,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (141,54,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (55,4,'MMSE_21',21,'延迟回忆','回忆「树木」','单选','DIRECT',1.0,1,21,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (142,55,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (143,55,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (56,4,'MMSE_22',22,'命名','命名：手表','单选','DIRECT',1.0,1,22,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (144,56,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (145,56,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (57,4,'MMSE_23',23,'命名','命名：铅笔','单选','DIRECT',1.0,1,23,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (146,57,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (147,57,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (58,4,'MMSE_24',24,'复述','复述「大家齐心协力拉紧绳」','单选','DIRECT',1.0,1,24,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (148,58,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (149,58,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (59,4,'MMSE_25',25,'阅读理解','念「请闭上您的眼睛」并照做（闭眼动作）','单选','DIRECT',1.0,1,25,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (150,59,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (151,59,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (60,4,'MMSE_26',26,'三步指令','右手拿纸','单选','DIRECT',1.0,1,26,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (152,60,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (153,60,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (61,4,'MMSE_27',27,'三步指令','双手对折','单选','DIRECT',1.0,1,27,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (154,61,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (155,61,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (62,4,'MMSE_28',28,'三步指令','放到左腿上','单选','DIRECT',1.0,1,28,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (156,62,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (157,62,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (63,4,'MMSE_29',29,'书写','写一个完整、有意义的句子','单选','DIRECT',1.0,1,29,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (158,63,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (159,63,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (64,4,'MMSE_30',30,'视空间','照图画出两个交叉的五边形（10 个角）','单选','DIRECT',1.0,1,30,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (160,64,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (161,64,'0','错误',0.0,0,1);
INSERT INTO `scale_cutoff` (`id`,`scale_id`,`cutoff_type`,`group_key`,`result_label`,`is_abnormal`,`edu_years_min`,`edu_years_max`,`min_score`,`max_score`,`threshold`,`sort_order`) VALUES (8,4,'EDUCATION','文盲','文盲（0 年）',1,0,0,NULL,NULL,17.0,0);
INSERT INTO `scale_cutoff` (`id`,`scale_id`,`cutoff_type`,`group_key`,`result_label`,`is_abnormal`,`edu_years_min`,`edu_years_max`,`min_score`,`max_score`,`threshold`,`sort_order`) VALUES (9,4,'EDUCATION','小学','小学（1-6 年）',1,1,6,NULL,NULL,20.0,1);
INSERT INTO `scale_cutoff` (`id`,`scale_id`,`cutoff_type`,`group_key`,`result_label`,`is_abnormal`,`edu_years_min`,`edu_years_max`,`min_score`,`max_score`,`threshold`,`sort_order`) VALUES (10,4,'EDUCATION','中学及以上','中学及以上（>6 年）',1,7,NULL,NULL,NULL,24.0,2);

-- --------------------------------------------------------------------------
-- 量表：蒙特利尔认知评估基础量表（中文版）（MOCA_B）  计分类型：ITEMIZED
-- --------------------------------------------------------------------------
INSERT INTO `scale` (`id`,`code`,`name`,`full_name`,`version`,`summary`,`instruction`,`scoring_type`,`score_min`,`score_max`,`remark`) VALUES (5,'MOCA_B','蒙特利尔认知评估基础量表（中文版）','Montreal Cognitive Assessment - Basic (MoCA-B)','1.0','Nasreddine 等 2004 年编制、2014 年推出基础版，用于快速筛查 MCI，适用于文盲与低教育老人，满分 30 分。','涵盖执行功能、词语流畅性、定向、计算、抽象、延迟回忆、视知觉、命名、注意等认知域。节点（异常值指小于等于节点）：文盲/小学 19 分、中学 22 分、大学 24 分。','ITEMIZED',0.0,30.0,'抽象题「橘子香蕉」为练习、不计分；即刻回忆不计分。');
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (65,5,'MOCA_B_01',1,'执行功能','执行功能（连线）：按数字到点逐渐升高的顺序连线','单选','DIRECT',1.0,1,1,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (162,65,'1','完全按顺序连线',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (163,65,'0','出现任何错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (66,5,'MOCA_B_02',2,'词语流畅性','词语流畅性：1 分钟内说出水果名称','单选','DIRECT',2.0,1,2,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (164,66,'2','≥13 个',2.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (165,66,'1','8-12 个',1.0,0,1);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (166,66,'0','≤7 个',0.0,0,2);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (67,5,'MOCA_B_03',3,'定向','现在是几点钟？','单选','DIRECT',1.0,1,3,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (167,67,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (168,67,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (68,5,'MOCA_B_04',4,'定向','现在是哪一年？','单选','DIRECT',1.0,1,4,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (169,68,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (170,68,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (69,5,'MOCA_B_05',5,'定向','现在是几月份？','单选','DIRECT',1.0,1,5,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (171,69,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (172,69,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (70,5,'MOCA_B_06',6,'定向','今天是星期几？','单选','DIRECT',1.0,1,6,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (173,70,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (174,70,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (71,5,'MOCA_B_07',7,'定向','这是什么地方（医院/诊所/办公室名称）？','单选','DIRECT',1.0,1,7,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (175,71,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (176,71,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (72,5,'MOCA_B_08',8,'定向','在哪个城市？','单选','DIRECT',1.0,1,8,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (177,72,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (178,72,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (73,5,'MOCA_B_09',9,'计算','计算：用 1 元/5 元/10 元组合支付 13 元（给出付款方式数）','单选','DIRECT',3.0,1,9,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (179,73,'3','提供 3 种付款方式',3.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (180,73,'2','提供 2 种付款方式',2.0,0,1);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (181,73,'1','提供 1 种付款方式',1.0,0,2);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (182,73,'0','未提供正确付款方式',0.0,0,3);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (74,5,'MOCA_B_10',10,'抽象','火车和轮船属于什么类别？','单选','DIRECT',1.0,1,10,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (183,74,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (184,74,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (75,5,'MOCA_B_11',11,'抽象','锣鼓和笛子属于什么类别？','单选','DIRECT',1.0,1,11,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (185,75,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (186,75,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (76,5,'MOCA_B_12',12,'抽象','南方和北方属于什么类别？','单选','DIRECT',1.0,1,12,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (187,76,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (188,76,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (77,5,'MOCA_B_13',13,'延迟回忆','延迟回忆：一种花（桃花）','单选','DIRECT',1.0,1,13,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (189,77,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (190,77,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (78,5,'MOCA_B_14',14,'延迟回忆','延迟回忆：一种蔬菜（洋葱）','单选','DIRECT',1.0,1,14,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (191,78,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (192,78,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (79,5,'MOCA_B_15',15,'延迟回忆','延迟回忆：一种家具（桌子）','单选','DIRECT',1.0,1,15,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (193,79,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (194,79,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (80,5,'MOCA_B_16',16,'延迟回忆','延迟回忆：一种颜色（蓝色）','单选','DIRECT',1.0,1,16,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (195,80,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (196,80,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (81,5,'MOCA_B_17',17,'延迟回忆','延迟回忆：一种厨房用具（筷子）','单选','DIRECT',1.0,1,17,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (197,81,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (198,81,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (82,5,'MOCA_B_18',18,'视知觉','视知觉：在重叠图片中找出物品（共 10 件）','单选','DIRECT',3.0,1,18,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (199,82,'3','找出 9-10 个',3.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (200,82,'2','找出 6-8 个',2.0,0,1);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (201,82,'1','找出 4-5 个',1.0,0,2);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (202,82,'0','找出 3 个或以下',0.0,0,3);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (83,5,'MOCA_B_19',19,'命名','命名：斑马','单选','DIRECT',1.0,1,19,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (203,83,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (204,83,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (84,5,'MOCA_B_20',20,'命名','命名：孔雀','单选','DIRECT',1.0,1,20,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (205,84,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (206,84,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (85,5,'MOCA_B_21',21,'命名','命名：老虎','单选','DIRECT',1.0,1,21,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (207,85,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (208,85,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (86,5,'MOCA_B_22',22,'命名','命名：蝴蝶','单选','DIRECT',1.0,1,22,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (209,86,'1','正确',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (210,86,'0','错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (87,5,'MOCA_B_23',23,'注意','注意（白底）：只读圆形中的数字','单选','DIRECT',1.0,1,23,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (211,87,'1','完全正确或只有一次错误',1.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (212,87,'0','2 个或以上错误',0.0,0,1);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (88,5,'MOCA_B_24',24,'注意','注意（黑底）：只读圆形和正方形中的数字','单选','DIRECT',2.0,1,24,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (213,88,'2','2 个或以下错误',2.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (214,88,'1','3 个错误',1.0,0,1);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (215,88,'0','4 个或以上错误',0.0,0,2);
INSERT INTO `scale_cutoff` (`id`,`scale_id`,`cutoff_type`,`group_key`,`result_label`,`is_abnormal`,`edu_years_min`,`edu_years_max`,`min_score`,`max_score`,`threshold`,`sort_order`) VALUES (11,5,'EDUCATION','文盲/小学','文盲/小学（≤6 年）',1,0,6,NULL,NULL,19.0,0);
INSERT INTO `scale_cutoff` (`id`,`scale_id`,`cutoff_type`,`group_key`,`result_label`,`is_abnormal`,`edu_years_min`,`edu_years_max`,`min_score`,`max_score`,`threshold`,`sort_order`) VALUES (12,5,'EDUCATION','中学','中学（7-12 年）',1,7,12,NULL,NULL,22.0,1);
INSERT INTO `scale_cutoff` (`id`,`scale_id`,`cutoff_type`,`group_key`,`result_label`,`is_abnormal`,`edu_years_min`,`edu_years_max`,`min_score`,`max_score`,`threshold`,`sort_order`) VALUES (13,5,'EDUCATION','大学','大学（>12 年）',1,13,NULL,NULL,NULL,24.0,2);

-- --------------------------------------------------------------------------
-- 量表：临床痴呆评定量表（CDR）  计分类型：CDR
-- --------------------------------------------------------------------------
INSERT INTO `scale` (`id`,`code`,`name`,`full_name`,`version`,`summary`,`instruction`,`scoring_type`,`score_min`,`score_max`,`remark`) VALUES (6,'CDR','临床痴呆评定量表','Clinical Dementia Rating (CDR)','1.0','对 6 个功能域（记忆力、定向力、判断与解决问题、社会事务、家务与业余爱好、个人自理）分别评定，综合得出整体 CDR 评分与 CDR-SB。','分别对知情者和受试者本人进行访谈。只有当能力的减退是由认知障碍引起时才计分。6 个功能域各记 0 / 0.5 / 1 / 2 / 3 分；以记忆力为主要项目、其余 5 项为次要项目，按 Morris 规则综合出整体 CDR；CDR-SB = 6 域得分之和。','CDR',0.0,3.0,'CDR 整体评分与 CDR-SB 由算法计算，详见 scoring/scales/cdr.py。');
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (89,6,'CDR_MEMORY',1,'记忆力','记忆力（主要项目）','单选','DIRECT',3.0,1,1,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (216,89,'0','无记忆缺损或只有轻微的、偶尔的健忘',0.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (217,89,'0.5','经常性的轻微健忘；对事情能部分回忆；「良性健忘」',0.5,0,1);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (218,89,'1','中度记忆缺损，对近事遗忘突出，记忆缺损妨碍日常活动',1.0,0,2);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (219,89,'2','严重记忆缺损；能记住过去非常熟悉的事情，新发生的事件很快遗忘',2.0,0,3);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (220,89,'3','严重记忆丧失；仅存片段的记忆',3.0,0,4);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (90,6,'CDR_ORIENTATION',2,'定向力','定向力','单选','DIRECT',3.0,1,2,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (221,90,'0','能完全正确定向',0.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (222,90,'0.5','对时间关联性有轻微的困难，其余能完全正确定向',0.5,0,1);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (223,90,'1','对时间关联性有中度困难；检查时对地点仍有定向能力；但在某些场合可能有地理定向能力障碍',1.0,0,2);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (224,90,'2','对时间关联性有严重困难；通常对时间不能定向，常有地点失定向',2.0,0,3);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (225,90,'3','仅对病人自己有定向力',3.0,0,4);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (91,6,'CDR_JUDGMENT',3,'判断与解决问题','判断与解决问题的能力','单选','DIRECT',3.0,1,3,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (226,91,'0','能很好地解决日常问题，处理事务和财务，判断力良好',0.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (227,91,'0.5','在解决问题、辨别事物间的异同点方面有轻微缺损',0.5,0,1);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (228,91,'1','在解决问题、辨别事物间的异同点方面有中度困难；通常还能维持社交事务判断力',1.0,0,2);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (229,91,'2','在解决问题、辨别事物间的异同点方面有严重损害；社会判断力通常受损',2.0,0,3);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (230,91,'3','不能做判断，或不能解决问题',3.0,0,4);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (92,6,'CDR_COMMUNITY',4,'社会事务','社会事务','单选','DIRECT',3.0,1,4,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (231,92,'0','和平常一样能独立处理工作、购物、义务劳动及社会群体活动',0.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (232,92,'0.5','在这些活动方面仅有轻微损害',0.5,0,1);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (233,92,'1','已不能独立进行这些活动；可以从事其中部分活动，不经意的观察似乎正常',1.0,0,2);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (234,92,'2','不能独立进行室外活动；但可被带到家庭以外的场所参加活动',2.0,0,3);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (235,92,'3','不能独立进行室外活动；病重得不能被带到家庭以外的场所参加活动',3.0,0,4);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (93,6,'CDR_HOME',5,'家务与业余爱好','家务与业余爱好','单选','DIRECT',3.0,1,5,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (236,93,'0','家庭生活、业余爱好和需用智力的兴趣均很好保持',0.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (237,93,'0.5','家庭生活、业余爱好和需用智力的兴趣有轻微损害',0.5,0,1);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (238,93,'1','家庭活动有肯定的轻度障碍，放弃难度大的家务，放弃复杂的爱好和兴趣',1.0,0,2);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (239,93,'2','仅能做简单的家务，兴趣明显受限，而且维持的差',2.0,0,3);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (240,93,'3','丧失有意义的家庭活动',3.0,0,4);
INSERT INTO `scale_item` (`id`,`scale_id`,`item_code`,`item_no`,`domain`,`item_text`,`item_type`,`score_method`,`max_score`,`required`,`sort_order`,`remark`) VALUES (94,6,'CDR_PERSONAL_CARE',6,'个人自理','个人自理能力','单选','DIRECT',3.0,1,6,'');
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (241,94,'0','完全自理',0.0,0,0);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (242,94,'0.5','完全自理',0.5,0,1);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (243,94,'1','须旁人督促或提醒',1.0,0,2);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (244,94,'2','穿衣、个人卫生及个人事务料理都需要帮助',2.0,0,3);
INSERT INTO `scale_option` (`id`,`item_id`,`option_code`,`option_text`,`score_value`,`is_na`,`sort_order`) VALUES (245,94,'3','个人自理方面依赖别人给予很大帮助；经常大小便失禁',3.0,0,4);

COMMIT;

-- 数据量统计（执行后可核对）：scale 6 行；scale_item 94 行；scale_cutoff 13 行。
